# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib stacio, .registration = TRUE
NULL

rust_read_stac <- function(file) .Call(wrap__rust_read_stac, file)

#' Get the STAC type of a Value
#'
#' @param value The Value to get the type of
#'
#' @return An external pointer
get_stac_type <- function(value) .Call(wrap__get_stac_type, value)

rust_get_links <- function(value) .Call(wrap__rust_get_links, value)

rust_get_version <- function(value) .Call(wrap__rust_get_version, value)

rust_get_extensions <- function(value) .Call(wrap__rust_get_extensions, value)

rust_get_id <- function(value) .Call(wrap__rust_get_id, value)

rust_get_properties <- function(value) .Call(wrap__rust_get_properties, value)

rust_get_assets <- function(value) .Call(wrap__rust_get_assets, value)

rust_clone_pointer <- function(value) .Call(wrap__rust_clone_pointer, value)

rust_get_additional_fields <- function(value) .Call(wrap__rust_get_additional_fields, value)

rust_get_bbox <- function(value) .Call(wrap__rust_get_bbox, value)

rust_get_collection <- function(value) .Call(wrap__rust_get_collection, value)

StacObject <- new.env(parent = emptyenv())

StacObject$rust_clone_pointer <- function() .Call(wrap__StacObject__rust_clone_pointer, self)

StacObject$rust_get_links <- function() .Call(wrap__StacObject__rust_get_links, self)

StacObject$rust_get_version <- function() .Call(wrap__StacObject__rust_get_version, self)

StacObject$rust_get_extensions <- function() .Call(wrap__StacObject__rust_get_extensions, self)

StacObject$rust_get_id <- function() .Call(wrap__StacObject__rust_get_id, self)

StacObject$rust_get_properties <- function() .Call(wrap__StacObject__rust_get_properties, self)

StacObject$rust_get_assets <- function() .Call(wrap__StacObject__rust_get_assets, self)

StacObject$rust_get_additional_fields <- function() .Call(wrap__StacObject__rust_get_additional_fields, self)

StacObject$rust_get_bbox <- function() .Call(wrap__StacObject__rust_get_bbox, self)

StacObject$rust_get_collection <- function() .Call(wrap__StacObject__rust_get_collection, self)

#' @export
`$.StacObject` <- function (self, name) { func <- StacObject[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StacObject` <- `$.StacObject`

# nolint end
