# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib stacio, .registration = TRUE
NULL

rust_read_stac <- function(file) .Call(wrap__rust_read_stac, file)

#' Get the STAC type of a Value
#'
#' @param value The Value to get the type of
#'
#' @return An external pointer
rust_get_type_name <- function(value) .Call(wrap__rust_get_type_name, value)

rust_get_links <- function(value) .Call(wrap__rust_get_links, value)

rust_get_version <- function(value) .Call(wrap__rust_get_version, value)

rust_get_extensions <- function(value) .Call(wrap__rust_get_extensions, value)

rust_get_id <- function(value) .Call(wrap__rust_get_id, value)

rust_get_properties <- function(value) .Call(wrap__rust_get_properties, value)

rust_get_assets <- function(value) .Call(wrap__rust_get_assets, value)

rust_clone_pointer <- function(value) .Call(wrap__rust_clone_pointer, value)

rust_get_additional_fields <- function(value) .Call(wrap__rust_get_additional_fields, value)

rust_get_bbox <- function(value) .Call(wrap__rust_get_bbox, value)

rust_get_collection <- function(value) .Call(wrap__rust_get_collection, value)

rust_get_geometry <- function(value) .Call(wrap__rust_get_geometry, value)

rust_get_title <- function(value) .Call(wrap__rust_get_title, value)

rust_get_description <- function(value) .Call(wrap__rust_get_description, value)

rust_get_keywords <- function(value) .Call(wrap__rust_get_keywords, value)

rust_get_license <- function(value) .Call(wrap__rust_get_license, value)

rust_get_providers <- function(value) .Call(wrap__rust_get_providers, value)

rust_get_summaries <- function(value) .Call(wrap__rust_get_summaries, value)

rust_get_extent <- function(value) .Call(wrap__rust_get_extent, value)

# nolint end
